### ISSUE TITLE
Fix device enumeration on Safari

### ISSUE THREAD

**Issue by chadwallacehart** [webrtcHacks/WebRTC-Camera-Resolution#6]
Expected behavior: all available cameras are listed
Current behavior: only the default camera is listed

Need to ask for permission first, then redo `navigator.mediaDevices.enumerateDevices` after the user has accepted. Otherwise the user needs to manually `allow` camera permissions inside Safari:
![image](https://user-images.githubusercontent.com/6531125/44958483-e687c480-aeae-11e8-93ca-304cf2514019.png)

**Comment by octavn** [comment]
I can confirm. 

The user needs to manually `allow` camera permissions inside Safari before more than one camera or the camera names are shown in the list. 

Even refreshing after previously `allowing` produces the same list with only 1 generic webcam.

**Comment by chadwallacehart** [comment]
This should be fixed with the push I made a few minutes ago. Please try it at https://webrtchacks.github.io/WebRTC-Camera-Resolution/

**Comment by octavn** [comment]
It's fixed. Tried both Safari on macOS and on iOS.
